[package]
name = "permitter_common"
version = "0.1.0"
authors = ["Adam Perkowski <adas1per@protonmail.com>", "Raphaël Thériault <raphael_theriault@outlook.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0.41"
[dependencies.serde]
version = "1.0.102"
features = ["derive"]
